### ISSUE TITLE
Stop using options.txt for saving options

### ISSUE THREAD

**Issue by NukelordPvP** [PercyDan54/BorderRemover#1]
I cant get The Farlands to generate on my 1.17 server at spawn/in the world at all because servers don't support options.txt and your mod uses options.txt instead of a config file for settings can you please fix.

**Comment by PercyDan54** [comment]
I'm not familiar with server.
Can I use server.properties instead?

**Comment by Cyclopropinon** [comment]
can sb upload an example server.properties (preferrably from 1.19) so i can configure my own server.properties befor launching the server

**Comment by PercyDan54** [comment]
> can sb upload an example server.properties (preferrably from 1.19) so i can configure my own server.properties befor launching the server
``` #Minecraft server properties
#Sun Mar 12 09:16:38 CST 2023
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=A Minecraft Server
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=false
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
initial-enabled-packs=vanilla
level-type=minecraft\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
```

**Comment by Cyclopropinon** [comment]
this sems to be a completely vanilla one.
i cant find any options described in the readme file...
wich of them actually comes from your mod?

**Comment by Cyclopropinon** [comment]
btw what happens with max-world-size? will it be completely ignored or will it set the world border a trillion if i choose so?
(because the vanilla default is still having the world border at around 30mil)

**Comment by Cyclopropinon** [comment]
> this sems to be a completely vanilla one. i cant find any options described in the readme file... wich of them actually comes from your mod?

nvm
only now do i know that u are saving things in the toml file i just discovered lol
