### ISSUE TITLE
1.19.3 World won't generate 

### ISSUE THREAD

**Issue by SparkdotIe** [PercyDan54/BorderRemover#17]
### Type

Game behaviour

### Bug description

Trying to load up a 1.19.3 world with Fabric Loader 0.15.3, Cloth config 9.1.104, Fabric API 0.75.1, Mod Menu 5.1.0, and this mod's latest release here (1.0.6). Leads to the world generation either not happening at all, or failing after getting a few % of the spawn area loaded.

I have the farlands option enabled, and set their offset to 100406586 as is recommended, and have tried a few other values to see if they helped, but got the same response from the game where it just doesn't generate the world.

Logs: https://mclo.gs/vm44cyV

I do hope that this can get fixed, or I can be pointed to how I did something wrong. I wanted to make an smp in the farlands and this seems to be the only mod that enables them and disables the world boarder beyond 1.17+

### Screenshots or videos

![image](https://github.com/PercyDan54/BorderRemover/assets/26665237/a9031f60-c043-46b9-be60-4265ff52e5d4)
![image](https://github.com/PercyDan54/BorderRemover/assets/26665237/e487f39b-e274-4a0c-90c2-e6e376fc1c92)
![image](https://github.com/PercyDan54/BorderRemover/assets/26665237/95aa670d-01d1-481e-bc85-1114ca9e75c7)

### Minecraft Version

1.19.3

**Comment by PercyDan54** [comment]
I am unable to reproduce with 1.19.4:
	- borderremover 1.0.6
	- cloth-basic-math 0.6.1
	- cloth-config 10.1.105
	- fabric-api 0.87.2+1.19.4
	- fabricloader 0.15.3
	- java 17
	- minecraft 1.19.4
	- mixinextras 0.3.2
	- modmenu 6.3.1

**Comment by SparkdotIe** [comment]
I have upgraded to 1.19.4, but am still getting the issue. changing the offset value at all seems to do this. 
I'm running Java 17.0.8.1
Fabric api 0.87.2
Cloth Config 10.1.117
Boarderremover 1.0.6
Modmenu 6.3.1
Running through a Modrinth App instance

My CPU is an Intel i5-9300h
GPU is an Nvidia GeForce GTX 1050
16gb of ram total, 15 available
Minecraft has 8064mb allocated

Output logs: https://mclo.gs/hM5dIUe
and Latest.log file: [latest.log](https://github.com/PercyDan54/BorderRemover/files/13925238/latest.log)

Annoying as this is, I'm going to try 1.18/1.17 to see if those work, as I want the more classic farlands anyways.

**Comment by PercyDan54** [comment]
Ok it seems the 1.0.6 release was earlier than the terrain offset fix, will release a new one

**Comment by PercyDan54** [comment]
See new release

**Comment by PercyDan54** [comment]
You just said that you want to play mp with this mod. Make sure that everyone had this mod installed or they will get stuck once they go beyond 30000000

**Comment by SparkdotIe** [comment]
thank you, it seems to be working nicely now. Though it is a shame the mod is limited to 32 bits, meaning I can't bring the farther-er lands to the center of the world correctly. But that's not something I expect to be changed.

I will make sure everyone has the mod
