### ISSUE TITLE
Entitys beyond 30,000,512 are teleported back to said cordinate.

### ISSUE THREAD

**Issue by Thelaststandn** [PercyDan54/BorderRemover#18]
### Type

Game behaviour

### Bug description

1. Go any distance beyond 30,000,512
2. Spawn some entitys in, or just find some
3. Save & Quit the world
4. Re-enter the world
5. All entitys, including the player, are teleported back to 30,000,512 while retaining retaliative coordinates on the other axis, if not also beyond 30,000,512.

I'm fairly confident that 30,000,512 is where terrain stops generating on an unmodded client, so that probably has something to do with this.

### Screenshots or videos

![2024-01-17_22 57 23](https://github.com/PercyDan54/BorderRemover/assets/74090040/a4737702-5f16-4113-a2f9-da1ce76a5d91)

### Minecraft Version

1.20.1, Unknown if other versions are effected

**Comment by PercyDan54** [comment]
![QQ_1722041881339](https://github.com/user-attachments/assets/1b66d8ea-7f37-422b-8a8f-8973b51c269b)
Seems I forgot to patch this code, will fix
