### ISSUE TITLE
Cannot configure BorderRemover for far lands etc even with mod menu

### ISSUE THREAD

**Issue by TrillionDeTurtle** [PercyDan54/BorderRemover#3]
![NVIDIA_Share_J1kjza7wNj](https://user-images.githubusercontent.com/75444660/126625297-354729a5-d632-493a-94bb-70db0d8aa42f.png)

**Comment by PercyDan54** [comment]
Use the minecraft options screen

**Comment by PercyDan54** [comment]
I will reupload 1.0.3 with a modmenu integration later, please download again

**Comment by PercyDan54** [comment]
Should be resolved with 23f0763
