### ISSUE TITLE
1.18.2 Update

### ISSUE THREAD

**Issue by Jarfeh** [PercyDan54/BorderRemover#6]
Hello there! Is there a chance that this mod will be updated to 1.18.2? Thank you for making such a great mod :)

**Comment by PercyDan54** [comment]
I already made it work under 1.18 locally, will test again and push it

**Comment by PercyDan54** [comment]
A thing you'll need to know is due to 1.18 changed worldgen code, the coordinate scale factor of 684.412 is also changed and I couldn't find the new one. So coordinate scale changing is removed. Changing coordinate scale multiplier is still supported

**Comment by PercyDan54** [comment]
I pushed a release that should be working on 1.18
