### ISSUE TITLE
发现出现在1.18.2的新现象

### ISSUE THREAD

**Issue by wjr050430** [PercyDan54/BorderRemover#8]
如题，可能是因为世界生成器以及游戏机制的多次更改，出现了一些新的现象。
1.原边境之地（+12550824）出现地形抬高，出现巨大的石墙
![图片](https://user-images.githubusercontent.com/53849228/185763932-9d4daeff-cd55-40c1-ace4-7bc4077e89b7.png)
![图片](https://user-images.githubusercontent.com/53849228/185763942-9c3baa3d-1423-4aea-8928-e99c1a92fa12.png)
![图片](https://user-images.githubusercontent.com/53849228/185763952-1a027b79-9da3-464c-8da4-60b2e9e13a0a.png)
![图片](https://user-images.githubusercontent.com/53849228/185763966-1f730ad9-c871-4138-b7c5-4dfba00770e5.png)
![图片](https://user-images.githubusercontent.com/53849228/185763974-d5e9808a-1db0-4faa-bc97-5e389164d2ec.png)
2.玩家在>30000000之后会回弹，旁观者模式无此现象
3.区块大概在越过30000000后数百格停止生成

总结：我个人认为2，3项是1.18后机制更改，导致mod中对游戏的修改不起作用。第一条由于本人机器限制以及能力限制，尚不明确是什么情况

**Comment by PercyDan54** [comment]
2和3是bug，不知道为什么不改代码重新编译一遍就行

**Comment by PercyDan54** [comment]
你用的是https://github.com/PercyDan54/BorderRemover/releases/tag/1.0.4 吗？
我测试没有bug

**Comment by wjr050430** [comment]
> 

是这个版本，Loader版本是0.14.9

**Comment by PercyDan54** [comment]
我重新传了一遍1.0.4，再下载？
我是没发复现

**Comment by wjr050430** [comment]
下载最新版本后，问题2，3解决。
至于问题一，我认为是机制更改，导致mod对世界生成的更改有问题，所以和2，3一起提交了。

**Comment by wjr050430** [comment]
另外，我在这个版本发现了很多不同的现象，不知道作者有没有和MC考古圈合作再做一期1.18.2移除世界边境之后的探索呢？

**Comment by PercyDan54** [comment]
没有
边境之地随着世界生成更改是必然的，而且1.18应该也不会是唯一一个影响边境之地的版本
而且大致特征（出现坐标，规律）等都没变。

每一个新版本发一个有点咬打火机的意思
