### ISSUE TITLE
Rendering Issues Beyond 2^28 With Sodium

### ISSUE THREAD

**Issue by StereoMadnessss** [PercyDan54/BorderRemover#9]
For some reason rendering on certain side faces of blocks completely breaks down after 2^28, and this did not occur with FarLandsV2. 

Steps to Reproduce:
1. Teleport somewhere beyond 2^28 or somewhere around there
2. Look at the sides of blocks and you should see rendering problems occur

I do not know if this is GPU specific but it would be nice to fix it

**Comment by PercyDan54** [comment]
I can't see any render issues except it's known that after surpassing 33554432 the lighting system breaks

**Comment by StereoMadnessss** [comment]
It's an issue with Sodium and it's rendering as I tested without Sodium and it worked fine but with it the rendering issues occurred.

**Comment by PercyDan54** [comment]
I can't and will NOT solve compatibility issues, especially with optimisation mods.
